apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hasm-elm-example
  labels:
    name: hasm-elm-example
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: "RollingUpdate"  
  selector:
    matchLabels:
      name: "hasm-elm-example"
  template:
    metadata:
      labels:
        name: "hasm-elm-example"
        version: "1.0.0"
    spec:
      containers:
        - name: "hasm-elm-example"
          image: "gcr.io/hasm-elm-example/hasm-elm-example:v1"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: envvars
                  key: DB_HOST 
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: envvars
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: envvars
                  key: DB_PASSWORD 
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: envvars
                  key: DB_PORT
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: envvars
                  key: DB_SCHEMA
            - name: AUTH_JWK
              valueFrom:
                secretKeyRef:
                  name: envvars
                  key: AUTH_JWK        
          resources:
            requests:
              memory: 10Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /health
              port: external
            initialDelaySeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: external
            initialDelaySeconds: 5
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              name: "external"
              protocol: "TCP"
