kind: "Service"
apiVersion: "v1"
metadata:
  name: hasm-elm-example
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: external
  selector:
    app: hasm-elm-example
    tier: backend
